version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          R_LIBS_USER: ~/lib/R/library
          _R_CHECK_FORCE_SUGGESTS_: FALSE
          _R_CHECK_ASCII_DATA_: FALSE
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app -f test.Dockerfile .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - run:
          name: Test the app
          command: |
            docker run app R CMD check /autovar/autovar_0.2-4.tar.gz --no-manual --no-build-vignettes
      - run:
          name: Codecov the app
          command: |
            docker run -e CODECOV_TOKEN app Rscript -e 'covr::codecov()'
